<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateFeverHistoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fever_histories', function (Blueprint $table) {
            $table->id();
            $table->foreignId('patient_id')->references('id')->on('patients')
                ->constrained();
            $table->text('duration');
            $table->text('duration_units');
            $table->text('documentation');
            $table->text('temp_record');
            $table->text('temp_unit');
            $table->text('grade');
            $table->text('pattern');
            $table->text('pattern_details')->nullable();
            $table->text('general-sx');
            $table->text('rigors');
            $table->text('chills');
            $table->text('malaise');
            $table->text('night_sweats');
            $table->text('myalgias');
            $table->text('weightloss');
            $table->text('anorexia');
            $table->text('ageusia');
            $table->text('anosmia');
            $table->text('resp_sx');
            $table->text('runny_nose');
            $table->text('congested_nose');
            $table->text('sneezing');
            $table->text('nasal_discharge');
            $table->text('sore_throat');
            $table->text('odynophagia');
            $table->text('frontal_headache');
            $table->text('dry_cough');
            $table->text('productive_cough');
            $table->text('sputum_colour_details');
            $table->text('hemoptysis');
            $table->text('shortness_of_breath');
            $table->text('wheezing');
            $table->text('respirophasic_chest_pain');
            $table->text('respirophasic_chest_pain_site')->nullable();
            $table->text('hoarseness_of_voice');
            $table->text('halitosis');
            $table->text('loss_of_taste');
            $table->text('loss_of_smell');
            $table->text('altered_taste');
            $table->text('altered_smell');
            $table->text('nausea');
            $table->text('vomiting');
            $table->text('diarrhoea');
            $table->text('constipation');
            $table->text('pain_abdomen');
            $table->text('pain_abdomen_detail')->nullable();
            $table->text('jaundice');
            $table->text('abdominal_distension');
            $table->text('feeling_of_mass');
            $table->text('feeling_of_mass_detail')->nullable();
            $table->text('burning_micturition');
            $table->text('frequency');
            $table->text('urinary_urgency');
            $table->text('hematuria_urine');
            $table->text('pyuria');
            $table->text('urinary_incontinence');
            $table->text('lo_into_groin_pain');
            $table->text('lo_into_groin_pain_details')->nullable();
            $table->text('pain_lower_abdomen');
            $table->text('pain_lower_abdomen_details')->nullable();
            $table->text('periorbital_puffiness');
            $table->text('low_backache');
            $table->text('testicular_pain');
            $table->text('testicular_swelling');
            $table->text('uretheral_discharge');
            $table->text('uretheral_discharge_detail')->nullable();
            $table->text('illicitrelations');
            $table->text('lower_abdomina_pain');
            $table->text('painful_coitus');
            $table->text('pain_lower_abdomen_which_worsens_on_jarring_movements');
            $table->text('worsen_during_or_after_menses');
            $table->text('abnormal_vaginal_discharge');
            $table->text('post_coital_bleeding');
            $table->text('inter_menstrual_bleeding');
            $table->text('menhorrhagia');
            $table->text('breast_pain');
            $table->text('abnormal_nipple_discharge');
            $table->text('headache');
            $table->text('neck_stiffness');
            $table->text('pain_in_neck');
            $table->text('syncope');
            $table->text('altered_sesnorium');
            $table->text('irrelevant_talk');
            $table->text('fits');
            $table->text('decmemory');
            $table->text('ataxia');
            $table->text('double_vision');
            $table->text('ptosis');
            $table->text('weakness_of_any_part_of_body');
            $table->text('weakness_of_any_part_of_body_details')->nullable();
            $table->text('sensory_symptoms');
            $table->text('sensory_symptoms_details');
            $table->text('dec_vision');
            $table->text('dec_vision_details')->nullable();
            $table->text('facial_deviation_to');
            $table->text('facial_deviation_to_side');
            $table->text('easy_bruisibility');
            $table->text('spontaneous_bleeding');
            $table->text('epistaxis');
            $table->text('hemoptysis_hematology');
            $table->text('hemetemsis');
            $table->text('melena');
            $table->text('hematochezia');
            $table->text('hematurial_hematology');
            $table->text('abnormal_pv_bleeding');
            $table->text('others_bleeding')->nullable();
            $table->text('lumps_bumps_in_body');
            $table->text('lumps_bumps_in_body_details')->nullable();
            $table->text('symptoms_of_anemia');
            $table->text('rash');
            $table->text('rash_details')->nullable();
            $table->text('local_swelling_of');
            $table->text('local_swelling_detail')->nullable();
            $table->text('warm');
            $table->text('painful');
            $table->text('joint_pains');
            $table->text('joint_swelling');
            $table->text('joint_pain_swelling_details')->nullable();
            $table->text('muscle_pain');
            $table->text('muscle_spasm');
            $table->text('muscle_pain_spasm_detail')->nullable();
            $table->text('backache');
            $table->text('backache_detail')->nullable();
            $table->text('oral_ulcers');
            $table->text('alopecia');
            $table->text('photosesnitvity');
            $table->text('rash_on_face');
            $table->text('rash_on_face_details')->nullable();
            $table->text('proximal_myopathy');
            $table->text('red_or_purple_spots');
            $table->text('red_or_purple_spots_details')->nullable();
            $table->text('syncope_cvs');
            $table->text('syncope_cvs_detail')->nullable();
            $table->text('chest_pain');
            $table->text('dyspnoea');
            $table->text('orthopnea');
            $table->text('pnd');
            $table->text('palpitation');
            $table->text('dm');
            $table->text('htn');
            $table->text('ihd');
            $table->text('tb');
            $table->text('asthma');
            $table->text('hepatitis');
            $table->text('other_past_hx')->nullable();
            $table->text('past_surgical_hx')->nullable();
            $table->text('tb_contact');
            $table->text('family_member_with_similar_illness');
            $table->text('active_smoker');
            $table->text('ex_smoker');
            $table->text('alcoholic');
            $table->text('iv_drug_abuser');
            $table->text('other_addiction')->nullable();
            $table->text('illicit_relations');
            $table->text('promiscuous');
            $table->text('profession')->nullable();
            $table->text('colleague_has_similar_illness');
            $table->text('health_concerns_at_job')->nullable();
            $table->text('pet_animals_at_home');
            $table->text('pet_animals_at_home_details')->nullable();
            $table->text('patient_concerns')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fever_histories');
    }
}
