<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateFeverHistoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fever_histories', function (Blueprint $table) {
            $table->id();
            $table->foreignId('patient_id')->references('id')->on('users')
                ->constrained();
            $table->string('duration');
            $table->string('duration_units');
            $table->string('documentation');
            $table->string('temp_record');
            $table->string('temp_unit');
            $table->string('grade');
            $table->string('pattern');
            $table->string('pattern_details')->nullable();
            $table->string('general-sx');
            $table->string('rigors');
            $table->string('chills');
            $table->string('malaise');
            $table->string('night_sweats');
            $table->string('myalgias');
            $table->string('weightloss');
            $table->string('anorexia');
            $table->string('ageusia');
            $table->string('anosmia');
            $table->string('resp_sx');
            $table->string('runny_nose');
            $table->string('congested_nose');
            $table->string('sneezing');
            $table->string('nasal_discharge');
            $table->string('sore_throat');
            $table->string('odynophagia');
            $table->string('frontal_headache');
            $table->string('dry_cough');
            $table->string('productive_cough');
            $table->string('sputum_colour_details');
            $table->string('hemoptysis');
            $table->string('shortness_of_breath');
            $table->string('wheezing');
            $table->string('respirophasic_chest_pain');
            $table->string('respirophasic_chest_pain_site')->nullable();
            $table->string('hoarseness_of_voice');
            $table->string('halitosis');
            $table->string('loss_of_taste');
            $table->string('loss_of_smell');
            $table->string('altered_taste');
            $table->string('altered_smell');
            $table->string('nausea');
            $table->string('vomiting');
            $table->string('diarrhoea');
            $table->string('constipation');
            $table->string('pain_abdomen');
            $table->string('pain_abdomen_detail')->nullable();
            $table->string('jaundice');
            $table->string('abdominal_distension');
            $table->string('feeling_of_mass');
            $table->string('feeling_of_mass_detail')->nullable();
            $table->string('burning_micturition');
            $table->string('frequency');
            $table->string('urinary_urgency');
            $table->string('hematuria_urine');
            $table->string('pyuria');
            $table->string('urinary_incontinence');
            $table->string('lo_into_groin_pain');
            $table->string('lo_into_groin_pain_details')->nullable();
            $table->string('pain_lower_abdomen');
            $table->string('pain_lower_abdomen_details')->nullable();
            $table->string('periorbital_puffiness');
            $table->string('low_backache');
            $table->string('testicular_pain');
            $table->string('testicular_swelling');
            $table->string('uretheral_discharge');
            $table->string('uretheral_discharge_detail')->nullable();
            $table->string('illicitrelations');
            $table->string('lower_abdomina_pain');
            $table->string('painful_coitus');
            $table->text('pain_lower_abdomen_which_worsens_on_jarring_movements');
            $table->text('worsen_during_or_after_menses');
            $table->text('abnormal_vaginal_discharge');
            $table->text('post_coital_bleeding');
            $table->text('inter_menstrual_bleeding');
            $table->text('menhorrhagia');
            $table->text('breast_pain');
            $table->text('abnormal_nipple_discharge');
            $table->text('headache');
            $table->text('neck_stiffness');
            $table->text('pain_in_neck');
            $table->text('syncope');
            $table->text('altered_sesnorium');
            $table->text('irrelevant_talk');
            $table->text('fits');
            $table->text('decmemory');
            $table->text('ataxia');
            $table->text('double_vision');
            $table->text('ptosis');
            $table->text('weakness_of_any_part_of_body');
            $table->text('weakness_of_any_part_of_body_details')->nullable();
            $table->text('sensory_symptoms');
            $table->text('sensory_symptoms_details');
            $table->text('dec_vision');
            $table->text('dec_vision_details')->nullable();
            $table->text('facial_deviation_to');
            $table->text('facial_deviation_to_side');
            $table->text('easy_bruisibility');
            $table->text('spontaneous_bleeding');
            $table->text('epistaxis');
            $table->text('hemoptysis_hematology');
            $table->text('hemetemsis');
            $table->text('melena');
            $table->text('hematochezia');
            $table->text('hematurial_hematology');
            $table->text('abnormal_pv_bleeding');
            $table->text('others_bleeding')->nullable();
            $table->text('lumps_bumps_in_body');
            $table->text('lumps_bumps_in_body_details')->nullable();
            $table->text('symptoms_of_anemia');
            $table->text('rash');
            $table->text('rash_details')->nullable();
            $table->text('local_swelling_of');
            $table->text('local_swelling_detail')->nullable();
            $table->text('warm');
            $table->text('painful');
            $table->text('joint_pains');
            $table->text('joint_swelling');
            $table->text('joint_pain_swelling_details')->nullable();
            $table->text('muscle_pain');
            $table->text('muscle_spasm');
            $table->text('muscle_pain_spasm_detail')->nullable();
            $table->text('backache');
            $table->text('backache_detail')->nullable();
            $table->text('oral_ulcers');
            $table->text('alopecia');
            $table->text('photosesnitvity');
            $table->text('rash_on_face');
            $table->text('rash_on_face_details')->nullable();
            $table->text('proximal_myopathy');
            $table->text('red_or_purple_spots');
            $table->text('red_or_purple_spots_details')->nullable();
            $table->text('syncope_cvs');
            $table->text('syncope_cvs_detail')->nullable();
            $table->text('chest_pain');
            $table->text('dyspnoea');
            $table->text('orthopnea');
            $table->text('pnd');
            $table->text('palpitation');
            $table->text('dm');
            $table->text('htn');
            $table->text('ihd');
            $table->text('tb');
            $table->text('asthma');
            $table->text('hepatitis');
            $table->text('other_past_hx')->nullable();
            $table->text('past_surgical_hx')->nullable();
            $table->text('tb_contact');
            $table->text('family_member_with_similar_illness');
            $table->text('active_smoker');
            $table->text('ex_smoker');
            $table->text('alcoholic');
            $table->text('iv_drug_abuser');
            $table->text('other_addiction')->nullable();
            $table->text('illicit_relations');
            $table->text('promiscuous');
            $table->text('profession')->nullable();
            $table->text('colleague_has_similar_illness');
            $table->text('health_concerns_at_job')->nullable();
            $table->text('pet_animals_at_home');
            $table->text('pet_animals_at_home_details')->nullable();
            $table->text('patient_concerns')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fever_histories');
    }
}
