<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateIxSummariesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ix_summaries', function (Blueprint $table) {
            $table->id();
            $table->foreignId('patient_id')->references('id')->on('patients')
                ->constrained();
            $table->text('age');
            $table->text('sex');
            $table->text('weight');
            $table->text('height')->nullable();
            $table->text('bmi')->nullable();
            $table->text('sbp')->nullable();
            $table->text('dm');
            $table->text('dm_value')->nullable();
            $table->text('htn');
            $table->text('rx_htn');
            $table->text('ihd');
            $table->text('smoker');
            $table->text('smoker_value')->nullable();
            $table->text('investigation');
            $table->text('tlc')->nullable();
            $table->text('neutrophils')->nullable();
            $table->text('lymphocytes')->nullable();
            $table->text('alc')->nullable();
            $table->text('monocytes')->nullable();
            $table->text('eosinophils')->nullable();
            $table->text('rbc_count')->nullable();
            $table->text('hb')->nullable();
            $table->text('hct')->nullable();
            $table->text('mcv')->nullable();
            $table->text('mch')->nullable();
            $table->text('mchc')->nullable();
            $table->text('plt')->nullable();
            $table->text('esr')->nullable();
            $table->text('peripheral_smear')->nullable();
            $table->text('reticulocyte_count')->nullable();
            $table->text('bsf')->nullable();
            $table->text('bsr')->nullable();
            $table->text('hba1c')->nullable();
            $table->text('urea')->nullable();
            $table->text('cr')->nullable();
            $table->text('egfr')->nullable();
            $table->text('uric_acid')->nullable();
            $table->text('na')->nullable();
            $table->text('k')->nullable();
            $table->text('cl')->nullable();
            $table->text('ca')->nullable();
            $table->text('po4')->nullable();
            $table->text('mg')->nullable();
            $table->text('hco3')->nullable();
            $table->text('bilirubin')->nullable();
            $table->text('alt')->nullable();
            $table->text('ast')->nullable();
            $table->text('alk')->nullable();
            $table->text('protiens')->nullable();
            $table->text('albumin')->nullable();
            $table->text('globulins')->nullable();
            $table->text('agratio')->nullable();
            $table->text('amylase')->nullable();
            $table->text('lipase')->nullable();
            $table->text('cholestrol')->nullable();
            $table->text('triglycerides')->nullable();
            $table->text('ldl')->nullable();
            $table->text('hdl')->nullable();
            $table->text('vldl')->nullable();
            $table->text('non_hdl')->nullable();
            $table->text('tsh')->nullable();
            $table->text('ft3')->nullable();
            $table->text('ft4')->nullable();
            $table->text('final_risk')->nullable();
            $table->text('uacr')->nullable();
            $table->text('protien_uria')->nullable();
            $table->text('keton_uria')->nullable();
            $table->text('pus_cells')->nullable();
            $table->text('rbc')->nullable();
            $table->text('blood')->nullable();
            $table->text('hemoglobin_uria')->nullable();
            $table->text('ecg')->nullable();
            $table->text('echo')->nullable();
            $table->text('xray')->nullable();
            $table->text('ct')->nullable();
            $table->text('usg')->nullable();
            $table->text('others')->nullable();
            $table->text('investigation1');
            $table->text('investigation2');
            $table->text('logage')->nullable();
            $table->text('logage2')->nullable();
            $table->text('logtchol')->nullable();
            $table->text('loghdl')->nullable();
            $table->text('logagehdl')->nullable();
            $table->text('rx_htn_value')->nullable();
            $table->text('no_rx_htn_value')->nullable();
            $table->text('log_rx_bp')->nullable();
            $table->text('log_no_rx_bp')->nullable();
            $table->text('logage_log_rx_bp')->nullable();
            $table->text('logage_log_no_rx_bp')->nullable();
            $table->text('s0f')->nullable();
            $table->text('mnxbf')->nullable();
            $table->text('s0m')->nullable();
            $table->text('mnxbm')->nullable();
            $table->text('logage_dm')->nullable();
            $table->text('logage_smoker')->nullable();
            $table->text('gender_F')->nullable();
            $table->text('predict_F')->nullable();
            $table->text('cv_predict_F')->nullable();
            $table->text('female_risk')->nullable();
            $table->text('gender_M')->nullable();
            $table->text('predict_M')->nullable();
            $table->text('cv_predict_M')->nullable();
            $table->text('male_risk')->nullable();
            $table->text('aggregate_risk')->nullable();
            $table->text('percentage_risk')->nullable();
            $table->text('ascvd_risk')->nullable();
            $table->text('ra_factor_ict')->nullable();
            $table->text('raf_quantitative')->nullable();
            $table->text('anti_ccp')->nullable();
            $table->text('crp')->nullable();
            $table->text('das28esr')->nullable();
            $table->text('das28crp')->nullable();
            $table->text('tjc')->nullable();
            $table->text('sjc')->nullable();
            $table->text('gh')->nullable();
            $table->text('hbsag')->nullable();
            $table->text('anti_hcv')->nullable();
            $table->text('anti_hiv')->nullable();
            $table->text('iron_deficit')->nullable();
            $table->text('ldh')->nullable();
            $table->text('ch_lung_disease')->nullable();
            $table->text('hiv')->nullable();
            $table->text('call_score')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ix_summaries');
    }
}
